// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ChatWithDocument(arg1:string,arg2:string,arg3:Array<models.ChatMessage>):Promise<models.ChatResponse>;

export function ClearDoneQueue():Promise<void>;

export function ClearThumbnailCache():Promise<void>;

export function CreateCategory(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.Category>;

export function CreateDocument(arg1:models.CreateDocumentInput):Promise<models.Document>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteDocument(arg1:string):Promise<void>;

export function ExplainTerm(arg1:string,arg2:string,arg3:string):Promise<models.TermExplanation>;

export function GenerateFacebookCaption(arg1:string):Promise<models.CaptionResult>;

export function GetAppVersion():Promise<string>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetDBStats():Promise<Record<string, any>>;

export function GetDashboardStats():Promise<models.DashboardStats>;

export function GetDataDir():Promise<string>;

export function GetDocument(arg1:string):Promise<models.Document>;

export function GetDocuments(arg1:models.DocumentFilter):Promise<Array<models.Document>>;

export function GetLocalFileURL(arg1:string):Promise<string>;

export function GetQueueStatus():Promise<models.QueueStatus>;

export function GetReadingProgress(arg1:string):Promise<models.ReadingProgressDTO>;

export function GetRecentShareEvents(arg1:number):Promise<Array<models.ShareEvent>>;

export function GetSettings():Promise<Record<string, string>>;

export function GetUnlockedDocuments():Promise<Array<string>>;

export function IncrementViews(arg1:string):Promise<void>;

export function IsDocumentUnlocked(arg1:string):Promise<boolean>;

export function LogShareEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenBrowserURL(arg1:string):Promise<void>;

export function OpenFileInExplorer(arg1:string):Promise<void>;

export function PauseQueue():Promise<void>;

export function QueueFiles(arg1:Array<string>):Promise<Array<models.ImportQueueItem>>;

export function RebuildFTS():Promise<void>;

export function RunAIPipeline(arg1:string):Promise<void>;

export function SaveReadingProgress(arg1:models.ReadingProgressDTO):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function SearchDocuments(arg1:string):Promise<Array<models.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SetDocumentLock(arg1:string,arg2:boolean,arg3:number):Promise<void>;

export function StartQueue():Promise<void>;

export function TestAIConnection():Promise<void>;

export function UnlockDocument(arg1:string):Promise<void>;

export function UpdateDocument(arg1:string,arg2:models.UpdateDocumentInput):Promise<void>;
