// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatWithDocument'](arg1, arg2, arg3);
}

export function ClearDoneQueue() {
  return window['go']['main']['App']['ClearDoneQueue']();
}

export function ClearThumbnailCache() {
  return window['go']['main']['App']['ClearThumbnailCache']();
}

export function CreateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCategory'](arg1, arg2, arg3, arg4);
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function ExplainTerm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExplainTerm'](arg1, arg2, arg3);
}

export function GenerateFacebookCaption(arg1) {
  return window['go']['main']['App']['GenerateFacebookCaption'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetDBStats() {
  return window['go']['main']['App']['GetDBStats']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetDocuments(arg1) {
  return window['go']['main']['App']['GetDocuments'](arg1);
}

export function GetLocalFileURL(arg1) {
  return window['go']['main']['App']['GetLocalFileURL'](arg1);
}

export function GetQueueStatus() {
  return window['go']['main']['App']['GetQueueStatus']();
}

export function GetReadingProgress(arg1) {
  return window['go']['main']['App']['GetReadingProgress'](arg1);
}

export function GetRecentShareEvents(arg1) {
  return window['go']['main']['App']['GetRecentShareEvents'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUnlockedDocuments() {
  return window['go']['main']['App']['GetUnlockedDocuments']();
}

export function IncrementViews(arg1) {
  return window['go']['main']['App']['IncrementViews'](arg1);
}

export function IsDocumentUnlocked(arg1) {
  return window['go']['main']['App']['IsDocumentUnlocked'](arg1);
}

export function LogShareEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogShareEvent'](arg1, arg2, arg3);
}

export function OpenBrowserURL(arg1) {
  return window['go']['main']['App']['OpenBrowserURL'](arg1);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function PauseQueue() {
  return window['go']['main']['App']['PauseQueue']();
}

export function QueueFiles(arg1) {
  return window['go']['main']['App']['QueueFiles'](arg1);
}

export function RebuildFTS() {
  return window['go']['main']['App']['RebuildFTS']();
}

export function RunAIPipeline(arg1) {
  return window['go']['main']['App']['RunAIPipeline'](arg1);
}

export function SaveReadingProgress(arg1) {
  return window['go']['main']['App']['SaveReadingProgress'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['main']['App']['SearchDocuments'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SetDocumentLock(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetDocumentLock'](arg1, arg2, arg3);
}

export function StartQueue() {
  return window['go']['main']['App']['StartQueue']();
}

export function TestAIConnection() {
  return window['go']['main']['App']['TestAIConnection']();
}

export function UnlockDocument(arg1) {
  return window['go']['main']['App']['UnlockDocument'](arg1);
}

export function UpdateDocument(arg1, arg2) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2);
}
